/**
 * Generate 5 DOCX resume template stubs in data/templates/
 * Run: npx tsx scripts/generate-templates.ts
 */
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from "docx";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const OUTPUT_DIR = join(__dirname, "..", "data", "templates");

interface TemplateConfig {
  filename: string;
  title: string;
  subtitle: string;
  sections: string[];
  notes: string;
}

const templates: TemplateConfig[] = [
  {
    filename: "modern-minimal.docx",
    title: "Modern Minimal Resume",
    subtitle: "Clean single-column layout with subtle accents. Generous whitespace.",
    sections: ["Contact Information", "Professional Summary", "Experience", "Education", "Skills"],
    notes: "Best for: Design, Marketing, Startups. Use this template for a clean, contemporary look that lets your content breathe.",
  },
  {
    filename: "corporate.docx",
    title: "Corporate Resume",
    subtitle: "Traditional two-column format. Conservative styling.",
    sections: ["Contact Information", "Executive Summary", "Professional Experience", "Education & Certifications", "Core Competencies"],
    notes: "Best for: Finance, Consulting, Legal. This template follows traditional formatting expected in conservative industries.",
  },
  {
    filename: "creative-bold.docx",
    title: "Creative Bold Resume",
    subtitle: "Eye-catching color blocks and visual hierarchy.",
    sections: ["Contact & Portfolio", "Creative Summary", "Selected Work", "Education & Awards", "Skills & Tools"],
    notes: "Best for: Creative roles, Portfolios. Stand out with bold section headers and visual emphasis on your creative achievements.",
  },
  {
    filename: "tech-developer.docx",
    title: "Tech / Developer Resume",
    subtitle: "Monospace accents, skills matrix, project showcase sections.",
    sections: ["Contact & GitHub", "Technical Summary", "Technical Skills Matrix", "Professional Experience", "Projects & Open Source", "Education"],
    notes: "Best for: Software Engineers, DevOps, Data. Optimized for showcasing technical skills, project contributions, and engineering experience.",
  },
  {
    filename: "ats-optimized.docx",
    title: "ATS-Optimized Resume",
    subtitle: "Maximum ATS compatibility. Simple formatting, standard headers.",
    sections: ["Contact Information", "Summary", "Work Experience", "Education", "Skills"],
    notes: "Best for: Any role — highest ATS pass rate. Uses only standard section headers and simple formatting for maximum compatibility with applicant tracking systems.",
  },
];

function generateDoc(config: TemplateConfig): Document {
  const sectionParagraphs = config.sections.flatMap((section) => [
    new Paragraph({
      text: section.toUpperCase(),
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 400, after: 100 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "999999" },
      },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `[Your ${section.toLowerCase()} goes here]`,
          italics: true,
          color: "888888",
        }),
      ],
      spacing: { after: 200 },
    }),
  ]);

  return new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: config.title,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: config.subtitle,
                italics: true,
                color: "666666",
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: config.notes,
                size: 18,
                color: "999999",
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          ...sectionParagraphs,
          new Paragraph({
            spacing: { before: 600 },
            children: [
              new TextRun({
                text: "— Generated by Resume Roaster Template Pack —",
                size: 16,
                color: "AAAAAA",
                italics: true,
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });
}

async function main() {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  for (const config of templates) {
    const doc = generateDoc(config);
    const buffer = await Packer.toBuffer(doc);
    const path = join(OUTPUT_DIR, config.filename);
    writeFileSync(path, buffer);
    console.log(`Generated: ${path}`);
  }

  console.log(`\nDone! ${templates.length} templates written to ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error("Failed to generate templates:", err);
  process.exit(1);
});
